### ISSUE TITLE
Request: Split this package in two: Rebus.ServiceProvider and Rebus.AspNetCore

### ISSUE THREAD

**Issue by alexdrl** [rebus-org/Rebus.ServiceProvider#14]
Hello, we are using this package in a Xamarin application, and seeing that the ASP.NET Core hosting DLLs are loading into the Xamarin app because the dependency in Rebus.ServiceProvider.

The Xamarin app only uses de AddRebus method. 

Could this be split in two packages? With some guidance, we could help with that.

**Comment by larsw** [comment]
Hi,

 I agree with @alexdrl - it would be nice if this package was split into two; it pulls in AspNetCore dependencies when they're not needed.

**Comment by mookid8000** [comment]
Is there any reason why this package should have a dependency on ASP.NET Core at all?

**Comment by larsw** [comment]
No, not really. IMHO it should only depend on Microsoft.Extensions.DependencyInjection and Rebus.

**Comment by mookid8000** [comment]
well, I guess that's pretty easy then.... 😄

**Comment by Hawxy** [comment]
@mookid8000 any plans to update this package?

Edit: I'm working on a PR for this.

**Comment by mookid8000** [comment]
@Hawxy 👍
