### ISSUE TITLE
Implement IHandleMessages<> in existing singleton

### ISSUE THREAD

**Issue by srollinet** [rebus-org/Rebus.ServiceProvider#15]
Hello,

I try to make an existing registered singleton implement IHandleMessages<>
How to register it correctly?

```
services.AddSingleton<IHostedService, MyService>();
services.AddSingleton<IHandleMessages<MyMessage>>(x => x.GetService<MyService>()); //Throws an exception when message is sent
//services.AutoRegisterHandlersFromAssemblyOf<MyService>(); //Creates a new instance everytime
services.AddRebus(configure => configure
    .Logging(l => l.Console())
    .Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "Local"))
    .Routing(r => r.TypeBased().Map<MyMessage>("Local"))
);
```

If I register it via `services.AutoRegisterHandlersFromAssemblyOf<MyService>();` a new instance is created everytime.
If I register it manually via `services.AddSingleton<IHandleMessages<MyMessage>>(x => x.GetService<MyService>());` I have an exception when the message is sent

> Value cannot be null. Parameter name: handler
>    at Rebus.Pipeline.Receive.HandlerInvoker`1..ctor(Func`1 action, Object handler, ITransactionContext transactionContext)
>    at Rebus.Pipeline.Receive.ActivateHandlersStep.<>c__DisplayClass4_0`1.<GetHandlerInvokers>b__0(IHandleMessages`1 handler)
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Rebus.Pipeline.Receive.ActivateHandlersStep.<GetHandlerInvokers>d__4`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Is this a bad idea to try to use an existing singleton? I can probably add a new class that implements the handler and where I inject my singleton service. But if it is possible I would like to avoid it.

**Comment by mookid8000** [comment]
> Is this a bad idea to try to use an existing singleton? 

Yes 😄 

Generally, it just makes the world easier to live in, when handlers and injected services are transient.

And then, once in a while, you need to register a singleton, but then please remember that everything that singleton gets injected _gets scoped to the lifestyle of the singleton_, meaning that the singleton must never have transient stuff injected.

I suggest you register the state that you need to share between handlers in a dedicated component, and then you let a reference to that be injected in your - transient! 😁 - handlers.

I hope it makes sense 😄
