### ISSUE TITLE
Handler of all failed messages by handling IFailed<object>

### ISSUE THREAD

**Issue by jens-jonsson** [rebus-org/Rebus.ServiceProvider#22]
Trying to create a handler to handle all failed messages by implementing `IHandleMessages<IFailed<object>>`.

Documentation suggests that implementing `IHandleMessages<object>` will call the handler for all messages but my constraint of IFailed<object> does not seem to create a match when resolving handlers.

I am on .net core using default IServiceProvider. Checking assembly scanning shows that my handler gets registered but not called for failed messages.

**Comment by Tsjunne** [comment]
Made a pull request with a proposed solution

**Comment by mookid8000** [comment]
Fixed in Rebus.ServiceProvider 5.0.2 🙂 Thanks @Tsjunne for your contribution! 👍
