### ISSUE TITLE
Use Microsoft.Extensions.Logging.ILogger with rebus

### ISSUE THREAD

**Issue by CzechsMix** [rebus-org/Rebus.ServiceProvider#24]
Is there currently a way to use ILogger with Rebus so that whatever logger I've configured for the rest of my app will be used by Rebus?

If there is not, would this be the correct repo to add such a feature?

**Comment by CzechsMix** [comment]
You can ignore the first question, I have a way to do it.

Just wondering if this is the right repo to add it.

**Comment by mookid8000** [comment]
You can use the [Rebus.Microsoft.Extensions.Logging](https://www.nuget.org/packages/Rebus.Microsoft.Extensions.Logging/) NuGet package.

Check the repository for an example on how to enable it: https://github.com/rebus-org/Rebus.Microsoft.Extensions.Logging
