### ISSUE TITLE
ServiceProvider handler registration on Rebus 6

### ISSUE THREAD

**Issue by fabiogusmao** [rebus-org/Rebus.ServiceProvider#26]
When upgrading to Rebus 6.0 I get the following error.

Code:
```
services.AutoRegisterHandlersFromAssemblyOf<CompanyIntegrationEventsHandler>();
```

Error:`
```
System.MissingMethodException: 'Method not found: 'Void Rebus.Extensions.EnumerableExtensions.ForEach(System.Collections.Generic.IEnumerable`1<!!0>, System.Action`1<!!0>)'.'
```

I am using the following NuGet packages and versions:

- Rebus 6.0.0 (works on 5.4.1)
- Rebus.Events 4.0.1
- Rebus.RabbitMq 5.2.0
- Rebus.Serilog 5.0.0
- Rebus.ServiceProvider 4.0.2

TIA

**Comment by mookid8000** [comment]
Should be fixed in Rebus.ServiceProvider 5.0.0
