### ISSUE TITLE
Question about Rebus.ServiceProvider + Rebus.Autofac.

### ISSUE THREAD

**Issue by VladislavMorozov** [rebus-org/Rebus.ServiceProvider#29]
Hello!
How to use  `app.ApplicationServices.UseRebus();`, if I registred rebus from autofac `builder.RegisterRebus();` ?

**Comment by mookid8000** [comment]
Check this out: 👉 https://github.com/rebus-org/Rebus.ServiceProvider#a-vanilla-console-app

**Comment by VladislavMorozov** [comment]
But this example to console app. I think is a too uncomfortable way for a web app.

**Comment by VladislavMorozov** [comment]
**
![image](https://user-images.githubusercontent.com/31768904/75884503-ff6f8e00-5e35-11ea-8281-70e006657f07.png)
**

I mean this is a problem to migrate from previous versions.

**Comment by mookid8000** [comment]
oh, sorry – if you scroll up a bit, then the example is for a web app: 👉  https://github.com/rebus-org/Rebus.ServiceProvider#in-aspnet-core-20-startupcs

**Comment by VladislavMorozov** [comment]
But I catch the exception. Look at the previous picture.

**Comment by VladislavMorozov** [comment]
I registered rebus from Rebus.Autofac `builder.RegisterRebus();` and use `app.ApplicationServices.UseRebus();` from Rebus.ServiceProvider.

https://user-images.githubusercontent.com/31768904/75884503-ff6f8e00-5e35-11ea-8281-70e006657f07.png

**Comment by mookid8000** [comment]
ah ok.... I got a little bit confused there.

You need to explain to me how Autofac and ServiceProvider work together in your scenario

**Comment by VladislavMorozov** [comment]
Ok, I will describe in new issue.
