### ISSUE TITLE
Unnecessary dependency on Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by jorenp** [rebus-org/Rebus.ServiceProvider#34]
Not really a bug, but a possible improvement. The existing dependency on `Microsoft.Extensions.DependencyInjection` could be replaced by `Microsoft.Extensions.DependencyInjection.Abstractions`. 

The only usage of a type from this package is in `ServiceCollectionExtensions.Handlers` and the signatures can be modified to use `IServiceCollection`.
![image](https://user-images.githubusercontent.com/11046831/77992660-cb00cc00-7326-11ea-8f52-4b8bf7ccc7de.png)

If welcome, I can create a PR for the change.

**Comment by mookid8000** [comment]
Great idea! PR is most welcome 🙂

**Comment by mookid8000** [comment]
fixed in Rebus.ServiceProvider 5.0.6
