### ISSUE TITLE
.NET 5.0

### ISSUE THREAD

**Issue by dariogriffo** [rebus-org/Rebus.ServiceProvider#37]
Are there any plans of adding net5.0?

App veyor has added VS 2019 Preview image see here

I forked the repo and all is looking good (ran both samples app) commit [here](https://github.com/dariogriffo/Rebus.ServiceProvider/commit/73e17d7fd4ea579581b10c5bd556bc81da27957d), I can do the same with Logging and Configuration libs and open PRs against let's say specific branches feature/net50 if you create them.

Thoughts?
Perhaps an rc-X version of the lib?

PS I have created an issue on Rebus that have closed already [here](https://github.com/rebus-org/Rebus/issues/907) but thiking better, the Rebus.* that rely on Microsoft.* packages are the ones required to be updated for the breaking versions.

**Comment by mookid8000** [comment]
Cool cool, I've created `feature/net50` as you suggested 🙂 will go to Logging and Configuration and do the same right away

**Comment by hellfirehd** [comment]
I guess we're looking for NET6.0 now. ETA?

**Comment by mookid8000** [comment]
Rebus.ServiceProvider has supported .NET 5 for a while now, and the 7 prerelease versions target .NET 6 as well... this issue should have been closed long ago, I guess 🙂

**Comment by mookid8000** [comment]
I've released it as Rebus.ServiceProvider 7.0.0 now 🙂

**Comment by hellfirehd** [comment]
Awesome!  Thank you so much!
