### ISSUE TITLE
Feature request: Possibility to add multiple rebus services from startup ConfigureServices

### ISSUE THREAD

**Issue by jfalameda** [rebus-org/Rebus.ServiceProvider#39]
Hi,

I noticed there is no straight forward possibility to configure multiple pipelines on Rebus for .NET. I saw the workaround you commented on another thread regarding using `BackgroundService`. This is problematic for most cases as the vast majority of services and configurations are declared one level up at `ConfigureServices` at  `Startup.cs`.

Do you have any other workarounds in mind to mitigate this issue?

Kind Regards,
José.

**Comment by mookid8000** [comment]
> Do you have any other workarounds in mind to mitigate this issue?

Not really, no.... but I was contemplating using [Nub](https://github.com/rebus-org/nub) to support registering multiple (keyed) `IBus` registrations somehow.

It should be done in a way where the `IBus` injected into Rebus handlers would always be the bus instance belonging to the receiver, and then one of the bus instances should somehow be appointed "the default bus", which would mean that it would be the one injected into everything else (MVC controllers, etc).

Did you have any thoughts similar to this? Or do you have other ideas?

**Comment by jfalameda** [comment]
Hi,

Yes, it worked great, thanks.
