### ISSUE TITLE
Add overload to `AddRebusHandler` for passing in the `Type` directly

### ISSUE THREAD

**Issue by zlepper** [rebus-org/Rebus.ServiceProvider#42]
Currently `AddRebusHandler()` either requires you to pass in a factory function, or use the generic overload. However oftentimes when loading stuff through reflection, you have access to the type, which rebus just grabs from the generic. I would love an overload that just allowed you to pass in the `Type` instance directly. I'll even add it myself, just want to confirm if it is wanted in the first place :)

**Comment by mookid8000** [comment]
You are absolutely right – and a PR is most welcome 🙂
