### ISSUE TITLE
Cannot use version 6.3.0 in netstandard2.0 due to bad version constraints

### ISSUE THREAD

**Issue by zlepper** [rebus-org/Rebus.ServiceProvider#47]
As per https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/, the package does support netstandard2.0. However the version constraints for this package is limitted to <3, even though it will work.

**Comment by mookid8000** [comment]
Excellent 👍 it's out as Rebus.ServiceProvider 6.3.1 now 🙂
