### ISSUE TITLE
ServiceProvider requires Microsoft.Extensions.DependencyInjection.Abstractions < 6.0.0

### ISSUE THREAD

**Issue by martijndormans** [rebus-org/Rebus.ServiceProvider#56]
I am using .Net 6 and I include the Microsoft.Extensions.DependencyInjections.Abstractions package version 6.0.0. When building my solution I get a warning that Rebus.ServiceProvider does not supprt this. Could this be updated? Currently using version 6.4.1 of the Rebuse.ServiceProvider package.

![image](https://user-images.githubusercontent.com/21689486/143843261-679e7482-47f4-4d00-9aa4-50b8f239ab5f.png)

**Comment by mookid8000** [comment]
Try 
```psh
update-package rebus.serviceprovider
```
'ing and see if it changes anything 🙂

**Comment by martijndormans** [comment]
Which version do you want me to pull version 7.0.0 ???

**Comment by mookid8000** [comment]
Yes 🙂
