### ISSUE TITLE
isPrimaryBus?

### ISSUE THREAD

**Issue by ktjn** [rebus-org/Rebus.ServiceProvider#59]
According to readme.md, this is supported. But it's nowhere to be find in the code. Is this a coming feature?

**Comment by ktjn** [comment]
Sorry, read the changelog which clearify things.

**Comment by mookid8000** [comment]
Yes, as you've probably discovered it's available in Rebus.ServiceProvider v8 , which is currently in preview.

The most recent version is [Rebus.ServiceProvider 8.0.0-b03](https://www.nuget.org/packages/Rebus.ServiceProvider/8.0.0-b03)

I'll release a proper version as soon as enough people (myself included – am currently using it in [Fleet Manager's](https://pro.rebus.fm/#fleet-manager) production environment) have tried it and had no problems with it.

**Comment by ktjn** [comment]
Thanks. This is the only feature I'm missing at the moment. Good job with rebus. Super easy to use and good error message.
