### ISSUE TITLE
Remove contraint on AutoRegisterHandlersFromAssemblyOf

### ISSUE THREAD

**Issue by rosieks** [rebus-org/Rebus.ServiceProvider#7]
Is there any reason why `THandler` here must be of type `IHandleMessages` in https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider/ServiceCollectionExtensions.Handlers.cs#L22

Now I have to choose one of my handlers. Instead of that I would like to be able to choose for example `Program` class or create marker intefaces e.g. `IAssembly`.

**Comment by mookid8000** [comment]
No reason, other than wanting to encourage the developer to pick an assembly with at least one handler type 🙂

**Comment by mookid8000** [comment]
Type constraint is removed in 4.0.1

which is out in a few minutes
