### ISSUE TITLE
.net 7 support?

### ISSUE THREAD

**Issue by SbiCA** [rebus-org/Rebus.ServiceProvider#72]
Hi @mookid8000 

I guess there should be an update to .NET 7 

``` xml
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="[3, 8)" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="[3, 8)" />
```

Would that be sufficient or are there other places in rebus that should be bumped?

**Comment by SbiCA** [comment]
Created a PR #73

**Comment by SbiCA** [comment]
@mookid8000 just upgraded all to .NET 7.0 works like a charm 👍 

Thx again

**Comment by mookid8000** [comment]
Good to hear 🙂
