### ISSUE TITLE
not compatible with dotnet8 keyd service

### ISSUE THREAD

**Issue by SimTsai** [rebus-org/Rebus.ServiceProvider#86]
[demo src](https://github.com/SimTsai/Rebus.ServiceProvider.KeydServices.git)
when use keyd services in dotnet 8,
AddRebus throw “This service descriptor is keyed. Your service provider may not support keyed services.”.

package version: 10.1.0
dotnet version: 8.0.0

**Comment by mookid8000** [comment]
Fixed by #87 , thanks! 🙂   It's out as Rebus.ServiceProvider 10.1.1 on NuGet.org now
