### ISSUE TITLE
Get another package IHostedService implementation in StartRebus method and start async

### ISSUE THREAD

**Issue by EMRBlackHe** [rebus-org/Rebus.ServiceProvider#88]
I trying to upgrade my project framework to the latest
When running the IntegrationTests case of the project, the StartRebus method in ServiceProviderExtensions will obtain the IHostedService implementation injected by another package and call it to start async.
.Net 8
Abp Vnext 8.0.3
Rebus 8.0.1
Rebus.ServiceProvoider 10.0.0

Please refer to the below,
The last object in the list object comes from the injection of Microsoft.AspNetCore.TestHost. When this implementation executes StartAsync, the OnApplicationInitialization method in the project will be executed again, and the StartAsync method will be called again.
This means that this running will be an infinite loop.
![image](https://github.com/rebus-org/Rebus.ServiceProvider/assets/104949423/d776df7b-0953-4121-a451-c64247ef7999)

I analyze that this change will fix this issue, but I am not sure whether other cases will be missed and new issues will be introduced by this change.
![image](https://github.com/rebus-org/Rebus.ServiceProvider/assets/104949423/0632794b-bd6c-4d65-b255-6a16becfb2b3)

**Comment by mookid8000** [comment]
Hi @EMRBlackHe , you're right, this is a problem!

Would you be interested in helping out with a PR? 🙂

**Comment by EMRBlackHe** [comment]
@mookid8000 
Glad to help

**Comment by EMRBlackHe** [comment]
The issue has been fixed in 10.1.2
