### ISSUE TITLE
It should be possible to access IServiceProvider from onCreated

### ISSUE THREAD

**Issue by srogovtsev** [rebus-org/Rebus.ServiceProvider#94]
Documentation shows [the following example](https://github.com/rebus-org/Rebus/wiki/Startup-shutdown#using-microsoftextensionsdependencyinjection):

```cs
services.AddRebus(
    configure => configure
        .Transport(...),

    onCreated: async bus => {
        await Task.WhenAll(
            bus.Subscribe<SomeEvent>(),
            bus.Subscribe<AnotherEvent>(),
            bus.Subscribe<LastEvent>()
        );
    }
);
```

This is nice, but in our case information required for the subscriptions is stored somewhere else in the DI container. I think that `onCreated` should accept `Func<IServiceProvider,IBus,Task>` instead of current `Func<IBus,Task>`.

From the brief glimpse at the code I can see that we definitely have access to the `IServiceProvider` at the moment of `onCreate` call, so this should be pretty straightforward.

https://github.com/rebus-org/Rebus.ServiceProvider/blob/2429f8cec05ff89d108837fda9db2da830073a11/Rebus.ServiceProvider/ServiceProvider/Internals/RebusInitializer.cs#L117-L121

I'll try to draft a PR later this week.

**Comment by mookid8000** [comment]
I've now added two additional `AddRebus` overloads that do what you requested 🙂 

It's out in Rebus.ServiceProvider 10.2.0 which is available on NuGet.org now.

**Comment by srogovtsev** [comment]
Thank you so much, and sorry for not getting back with that PR I've promised.

**Comment by mookid8000** [comment]
@srogovtsev no worries - it wasn't too hard 🙂
